@startuml
title Test Eurocode EN 1991-1-4 - Test Liens

start
:Déterminer la vitesse de référence vb,0;
note right
[[https://www.google.com Google]]
end note

:Calculer la pression dynamique qp(z);
note right
[[https://fr.wikipedia.org/wiki/Eurocode Wikipedia - Eurocode]]
end note

stop
@enduml
