name: TEST - PlantUML Diagrams

on:
  push:
    branches:
      - test-plantuml

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml graphviz

      - name: Generate diagrams (TEST)
        run: |
          mkdir -p docs
          for f in diagrams/*.puml; do
            plantuml -tsvg "$f" -o ../docs
          done
